package org.athmis.wmoptimisation.algos;

import java.util.List;

import org.apache.log4j.Logger;
import org.athmis.wmoptimisation.changeset.Change;
import org.athmis.wmoptimisation.osmserver.OsmServer;
import org.athmis.wmoptimisation.versuche.ChangeSetZipContentData;

/**
 * ChangeSetGenerator implementations are used for test of a changeset
 * generation algorithm. Architecture is <a
 * href="http://en.wikipedia.org/wiki/Template_method_pattern">Template method
 * pattern</a>.
 */
public abstract class ChangeSetGenerator {
	private static Logger LOGGER = Logger.getLogger(ChangeSetGenerator.class);
	private OsmServer osmServer;

	public ChangeSetGenerator() {
		osmServer = new OsmServer();
	}

	/**
	 * Stores all changes of given ChangeSetZipContentData object into a new
	 * ChangeSetZipContentData object. Uses specialized changeset generation
	 * algorithm to minimize the size of changesets.
	 * 
	 * @param changesFromZip
	 *            a set of (real) changes and changesets
	 * @return new storage of the changes, generated by implementations of the
	 *         template method
	 */
	public final ChangeSetZipContentData createOptimizedChangeSets(
			ChangeSetZipContentData changesFromZip) {
		List<Change> changes;
		ChangeSetZipContentData optimizedDataSet;

		optimizedDataSet = new ChangeSetZipContentData();
		changes = changesFromZip.getAllChanges();

		LOGGER.info("use " + changes.size() + " for optimization");

		for (Change change : changes) {
			add(change, osmServer, optimizedDataSet);
		}

		return optimizedDataSet;
	}

	/**
	 * Implementations of ChangeSetGerator must implement here their changeset
	 * generation algorithm.
	 * 
	 * @param change
	 *            this change is new and must be added to any changest
	 * @param osmServer
	 *            the OSM Server
	 * @param optimizedDataSet
	 *            the object wich stores the change and (generated) changesets,
	 *            the task of this object is to analyze the changests after all
	 *            changes added
	 */
	protected abstract void add(Change change, OsmServer osmServer,
			ChangeSetZipContentData optimizedDataSet);
}
